//Registration States
//Daniel Goodrum, Jan 2018

#ifndef REGISTRATIONSTATES_H
#define REGISTRATIONSTATES_H



enum class RegistrationState
{
	CURRENTLY_DEREGISTERED,
	PENDING_REGISTRION,
	CURRENTLY_REGISTERED,
	PENDING_DEREGISTRATION
};


#endif // !REGISTRATIONSTATES_H
